INSERT INTO event (name, location, city, date, organiser, imgpath, description, type) VALUES
('Unforgettable Festival 2025', 'Piața Constituției', 'București', '2025-09-11', 'Dream Events', 'unforgettable_2025.png', 'Festival cu Bocelli, Carreras, Zamfir, Jenkins.', 'fizic'),
('Cluj-Napoca: OVO by Cirque du Soleil', 'BTarena', 'Cluj-Napoca', '2025-04-23', 'Cirque du Soleil', 'ovo_cirque.jpg', 'Spectacol acrobatic – Cirque du Soleil.', 'fizic'),
('CODRU Festival 2025', 'Pădurea Verde', 'Timișoara', '2025-08-29', 'Codru Events', 'codru_2025.jpg', 'Festival de muzică și natură.', 'fizic'),
('Skunk Anansie la Arenele Romane', 'Arenele Romane', 'București', '2025-07-27', 'Live Nation', 'skunk_anansie.jpg', 'Concert rock Skunk Anansie.', 'fizic'),
('Joe Satriani & Steve Vai & SatchVai Band', 'Arenele Romane', 'București', '2025-07-23', 'Live Nation', 'satriani_vai.jpg', 'Guitar heroes: Satriani & Vai.', 'fizic'),
('BACK IN VAMA – Manifestul unei întoarceri', 'Vama Veche', 'Vama Veche', '2025-08-14', 'Vama Events', 'back_in_vama.jpg', 'Festival de revenire în Vama Veche.', 'fizic'),
('ARTmania Festival Sibiu 2025', 'Piața Mare', 'Sibiu', '2025-07-25', 'ARTmania Org.', 'artmania_2025.jpg', 'Festival internațional de rock și artă.', 'fizic'),
('Concert Jennifer Lopez (JLo)', 'Piața Constituției', 'București', '2025-07-27', 'MLD Events', 'jlo_bucharest.jpg', 'Show live Jennifer Lopez.', 'fizic'),
('Telefonul fără fir', 'Teatrul Vasilache', 'București', '2025-07-19', 'Teatru Vasilache', 'telefonul_fara_fir.jpg', 'Spectacol comic la Vasilache.', 'fizic'),
('Art, Drinks and Classical Strings', 'Palais Ghica Victoriei', 'București', '2025-08-29', 'Classical Events', 'classical_strings.jpg', 'Eveniment de muzică clasică și vin.', 'fizic'),
('Concert Scorpions la Romexpo', 'Romexpo', 'București', '2025-09-11', 'Scorpions Tour', 'scorpions_romexpo.jpg', 'Legendă rock: Scorpions.', 'fizic'),
('Focșani: Rock for Hope', 'Sala Polivalenta', 'Focșani', '2025-09-26', 'Hope Foundation', 'rock_for_hope.jpg', 'Concert caritabil Rock for Hope.', 'fizic'),
('Focus in The Park 2025', 'Parcul Sub Arini', 'Sibiu', '2025-08-28', 'Focus Events', 'focus_in_the_park.jpg', 'Festival pop-rock în Sibiu.', 'fizic'),
('Open Air Blues Festival Brezoi 2025', 'Summer Camp Brezoi', 'Brezoi', '2025-07-22', 'Brezoi Blues Org.', 'blues_brezoi.jpg', 'Festival blues outdoor.', 'fizic'),
('Dan Balan - Soundstalgic', 'Sala Palatului', 'București', '2025-10-30', 'Dan Balan Org.', 'dan_balan.jpg', 'Concert Dan Bălan.', 'fizic'),
('SMILEY @ SALA PALATULUI – “ARMONIE”', 'Sala Palatului', 'București', '2025-10-30', 'Smiley Music', 'smiley_armonie.jpg', 'Concert Smiley.', 'fizic'),
('Turneu: Alifantis & Zan 30 de ani', 'Sala Palatului', 'București', '2025-10-01', 'Alifantis & Zan Org.', 'alifantis_zan.jpg', 'Turneu aniversar 30 ani.', 'fizic'),
('B.U.G. Mafia în concert la BTarena', 'BTarena', 'Cluj-Napoca', '2025-12-13', 'B.U.G. Mafia Org.', 'bug_mafia.jpg', 'Concert B.U.G. Mafia.', 'fizic'),
('Tombola "Fotbalul Face Bine"', 'Arena Națională', 'București', '2025-11-20', 'Charity Events', 'tombola_fotbal.jpg', 'Tombolă caritabilă eveniment fotbal.', 'fizic'),
('Stand-up comedy cu Teo, Vio & Costel', 'Sala Palatului', 'București', '2025-09-25', 'Comedy Stars', 'standup_teo_vio_costel.jpg', 'Spectacol de stand-up.', 'fizic');